## Sprawozdanie1

**Data:** 2024-05-19  
**Autor:** Piotr Szepietowski

## Zadania działu 1

## Zadanie 1
Utwórz macierze **A** i **B** oraz wektor **f** określone jako:
$$
A = \begin{bmatrix}
2 & -7 \\
5 & 4 \\
\end{bmatrix} 
B = \begin{bmatrix}
6 & 1 \\
4 & -3 \\
\end{bmatrix} 
f = \begin{bmatrix}
4 \\
1 \\
\end{bmatrix} 
$$

In [63]:
import numpy as np

A = np.array([[2, -7], [5, 4]])
B = np.array([[6, 1], [4, -3]])
f = np.array([[4, 1]])

print(f"A = {A}")
print(f"B = {B}")
print(f"f = {f}")

A = [[ 2 -7]
 [ 5  4]]
B = [[ 6  1]
 [ 4 -3]]
f = [[4 1]]


## Zadanie 2

**a.** Wyświetl rozmiar macierzy **A** oraz wektora **f**.  
**b.** Dokonaj transpozycji macierzy **B**.  
**c.** Oblicz wyrażenie: $(A + B)^2 + 2(A - B)$  
**d.** Utwórz macierz $C = [A, B]$ oraz wektor $h = [f, f]$  
**e.** Oblicz iloczyn $C \cdot h$

In [ ]:
# a
print(f"Rozmiar macierzy A: {A.shape}")
print(f"Rozmiar wektora f: {f.shape}")

# b
print(f"Macierz B po transpozycji:\n{B.T}")

# c
print(f"Wynik operacji (A + B)^2 + 2(A - B):\n{np.linalg.matrix_power(A + B, 2) + 2 * (A - B)}")

# d
C = np.vstack((A, B))
print(f"Macierz C = np.vstack((A, B))\n{C}")
h = np.vstack((f.T, f.T))
print(f"Wektor h = np.vstack((f.T, f.T))\n{h}")

# e
print(f"Macierz C.T * h:\n{C.T @ h}\nNiemożliwe do obliczenia, ponieważ liczba kolumn macierzy C nie zgadza się z liczbą wierszy wektora h, więc mnożenie wykonano po transpozycji macierzy C.")

Rozmiar macierzy A: (2, 2)
Rozmiar wektora f: (1, 2)
Macierz B po transpozycji:
[[ 6  4]
 [ 1 -3]]
Wynik operacji (A + B)^2 + 2(A - B):
[[  2 -70]
 [ 83 -39]]
Macierz C = np.vstack((A, B))
[[ 2 -7]
 [ 5  4]
 [ 6  1]
 [ 4 -3]]
Wektor h = np.vstack((f.T, f.T))
[[4]
 [1]
 [4]
 [1]]
Macierz C.T * h:
[[ 41]
 [-23]]
