## Rozwiązywanie macierzy metodą Gaussa

In [7]:
import numpy as np
def Gauss(matrix, solutions):
    results = []
    for x in range(len(matrix)):
        for y in range(x + 1, len(matrix)):
            pivot = matrix[y][x] / matrix[x][x]
            for z in range(x, len(matrix)):
                matrix[y][z] -= matrix[x][z] * pivot
            solutions[y] -= solutions[x] * pivot
        results.append(solutions[x])
    return results
    

Gauss([[1,2,3],[4,5,6],[7,8,9]], [10, 11, 12])
Gauss([[1,9],[6,5]], [3,4])
Gauss([[9,8],[7,6]], [4,5])
Gauss(np.random.rand(100, 100), np.random.rand(100, 1))

[array([0.84031226]),
 array([-0.38169867]),
 array([0.09299838]),
 array([0.58908391]),
 array([1.55254434]),
 array([18.64094709]),
 array([-9.88860791]),
 array([-0.89666979]),
 array([-0.34108439]),
 array([-4.13103929]),
 array([-0.92608187]),
 array([0.90237582]),
 array([-1.43816325]),
 array([1.3263562]),
 array([18.56238325]),
 array([1.61911172]),
 array([-6.64563676]),
 array([-0.60843052]),
 array([1.42163676]),
 array([-5.13253153]),
 array([1.12261106]),
 array([1.35607155]),
 array([-6.983503]),
 array([-2.2411295]),
 array([0.53756944]),
 array([2.60713289]),
 array([-1.32168243]),
 array([-0.58870733]),
 array([0.34943494]),
 array([0.6434963]),
 array([-1.56736467]),
 array([-6.00818178]),
 array([-2.31170482]),
 array([-0.36082829]),
 array([-1.66696497]),
 array([0.37690519]),
 array([1.89312092]),
 array([4.36982288]),
 array([-48.07281069]),
 array([5.02467288]),
 array([-31.44760056]),
 array([2.22162031]),
 array([0.08209823]),
 array([-0.8155538]),
 array([34.3